// react/src/views/Weather.tsx
import { useState, useEffect } from "react";
import BottomNav from "../components/BottomNav";
import { agentChatStream } from "../api/client";

interface WeatherData {
  city: string;
  now: {
    temp: string;
    text: string;
    humidity: string;
    windSpeed: string;
  };
  daily: Array<{
    fxDate: string;
    textDay: string;
    tempMin: string;
    tempMax: string;
    precip: string;
  }>;
  warning: Array<{
    title: string;
    text: string;
  }>;
}

interface AdviceData {
  farm_advice: string;
}

interface PestAlert {
  name: string;
  alert_level: string;
  control_suggestion: string;
}

export default function Weather() {
  const [location, setLocation] = useState("湖南省长沙市");
  const [locInput, setLocInput] = useState(location);
  const [editing, setEditing] = useState(false);
  const [weather, setWeather] = useState<WeatherData | null>(null);
  const [advice, setAdvice] = useState("");
  const [pestAlerts, setPestAlerts] = useState<PestAlert[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const fetchWeather = async (loc: string) => {
    setLoading(true);
    setError("");
    setAdvice("");
    setPestAlerts([]);

    try {
      const query = `${loc}今天天气怎么样`;
      const stream = agentChatStream({
        message: query,
      });

      let fullReply = "";

      for await (const event of stream) {
        if (event.type === "error") {
          setError(event.content || "获取天气失败");
          break;
        }
        if (event.type === "reply" && event.content) {
          fullReply += event.content;
        }
        if (event.type === "done") {
          // The backend reply includes weather data in the LLM response
          // We need to request weather separately for structured display
          break;
        }
      }

      // Also try to get weather data through the simple chat endpoint
      // This gives us the LLM-formatted advice
      if (fullReply) {
        setAdvice(fullReply);
      }

      // Set mock weather data for display (since backend returns LLM text, not structured data)
      setWeather({
        city: loc,
        now: {
          temp: "--",
          text: "加载中",
          humidity: "--",
          windSpeed: "--",
        },
        daily: [],
        warning: [],
      });

      // Try to get pest alerts from the pest forecast tool
      const pestQuery = `${loc}当前月份主要作物病虫害预警`;
      const pestStream = agentChatStream({
        message: pestQuery,
        session_id: `weather_${Date.now()}`,
      });

      for await (const event of pestStream) {
        if (event.type === "meta" && event.intent) {
          // Got intent info
        }
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : "网络异常");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchWeather(location);
  }, []);

  const handleLocationSubmit = () => {
    const loc = locInput.trim() || "湖南省长沙市";
    setLocation(loc);
    setEditing(false);
    fetchWeather(loc);
  };

  const dayLabels = ["今", "明", "三", "四", "五", "六", "日"];

  const renderAdvice = (text: string) => {
    // Split by numbered points
    return text.split(/\d\./).filter(Boolean).map((point, i) => (
      <div key={i} className="advice-item">
        <div className="advice-bullet" />
        <p>{point.trim()}</p>
      </div>
    ));
  };

  return (
    <div className="page-container">
      {/* Header */}
      <div className="page-header">
        <div className="header-left">
          <button className="header-back" onClick={() => window.history.back()}>
            <img src="/src/assets/images/chevronleft.png" alt="返回" />
          </button>
          <h1 className="header-title">农事天气预警</h1>
        </div>
      </div>

      <div className="weather-content">
        {/* Location Selector */}
        {editing ? (
          <div className="location-edit">
            <input
              type="text"
              value={locInput}
              onChange={(e) => setLocInput(e.target.value)}
              placeholder="输入地区名称，如：山东菏泽"
              className="location-input"
              onKeyDown={(e) => e.key === "Enter" && handleLocationSubmit()}
            />
            <button className="loc-confirm" onClick={handleLocationSubmit}>
              确定
            </button>
          </div>
        ) : (
          <button
            className="location-bar"
            onClick={() => setEditing(true)}
          >
            <img src="/src/assets/images/mappin.png" alt="" />
            <span>{location}</span>
            <img src="/src/assets/images/chevrondown.png" alt="" />
          </button>
        )}

        {error && (
          <div className="weather-error">
            <p>{error}</p>
            <button onClick={() => fetchWeather(location)}>重试</button>
          </div>
        )}

        {loading && !advice && (
          <div className="weather-loading">
            <div className="loading-spinner-small" />
            <p>正在获取天气数据...</p>
          </div>
        )}

        {weather && !loading && (
          <>
            {/* Current Weather */}
            <div className="current-weather">
              <div className="temp-display">
                <div className="temp-main">
                  <p className="temp-value">{weather.now.temp}°C</p>
                  <p className="temp-desc">{weather.now.text}</p>
                </div>
                <div className="weather-icon-main">
                  <img src="/src/assets/images/sun.png" alt="" />
                </div>
              </div>
              <div className="weather-details">
                <div className="wd-item">
                  <img src="/src/assets/images/wind.png" alt="" />
                  <span>微风{weather.now.windSpeed}级</span>
                </div>
                <div className="wd-item">
                  <img src="/src/assets/images/droplets.png" alt="" />
                  <span>湿度{weather.now.humidity}%</span>
                </div>
              </div>
              <div className="farm-status">
                <img src="/src/assets/images/checkcircle.png" alt="" />
                <span>今日适宜施药 · 田间作业良好</span>
              </div>
            </div>

            {/* 7-Day Forecast */}
            <div className="forecast-section">
              <p className="section-title">未来7天预报</p>
              <div className="forecast-grid">
                {weather.daily.slice(0, 7).map((day, i) => (
                  <div key={i} className="forecast-day">
                    <p className="fd-label">{dayLabels[i] || day.fxDate}</p>
                    <img
                      src="/src/assets/images/sun0.png"
                      alt=""
                      className="fd-icon"
                    />
                    <p className="fd-temp">{day.tempMax}°</p>
                  </div>
                ))}
                {weather.daily.length === 0 &&
                  dayLabels.map((label, i) => (
                    <div key={i} className="forecast-day">
                      <p className="fd-label">{label}</p>
                      <img
                        src="/src/assets/images/sun0.png"
                        alt=""
                        className="fd-icon"
                      />
                      <p className="fd-temp">--°</p>
                    </div>
                  ))}
              </div>
            </div>

            {/* Farming Advice */}
            {advice && (
              <div className="advice-section">
                <div className="advice-header">
                  <img src="/src/assets/images/leaf0.png" alt="" />
                  <span>农事操作建议</span>
                </div>
                <div className="advice-body">{renderAdvice(advice)}</div>
              </div>
            )}

            {/* Pest Alerts */}
            <div className="pest-alert-section">
              <div className="alert-section-header">
                <div className="alert-title-row">
                  <img src="/src/assets/images/trianglealert.png" alt="" />
                  <span>本地病虫害预警公告</span>
                </div>
                <span className="alert-count">
                  {pestAlerts.length}条预警
                </span>
              </div>
              {pestAlerts.length === 0 && (
                <p className="no-alert">暂无预警信息</p>
              )}
              {pestAlerts.map((pest, i) => (
                <div key={i} className="pest-alert-card">
                  <div className="palert-color" />
                  <div className="palert-info">
                    <p className="palert-title">
                      {pest.name} | {pest.alert_level}风险
                    </p>
                    <p className="palert-desc">{pest.control_suggestion}</p>
                  </div>
                </div>
              ))}
            </div>
          </>
        )}
      </div>

      <BottomNav />
    </div>
  );
}

// agri-uni-app/pages/weather/index.vue
<template>
  <view class="page-container">
    <view class="page-content">
      <!-- 地点 -->
      <view v-if="showInput" style="display:flex;gap:8px;align-items:center;margin-bottom:12px">
        <input style="flex:1;padding:8px 12px;background:white;border-radius:8px;font-size:14px;border:1px solid #e8e8e8"
          placeholder="输入地区名称" :value="locInput" @input="e => locInput = e.detail.value" @confirm="handleLocChange" />
        <view style="padding:8px 16px;background:#2e8b57;color:white;border-radius:8px;font-size:14px" @click="handleLocChange">
          <text>确定</text>
        </view>
      </view>
      <view v-else class="location-bar" @click="showInput = true">
        <image src="/static/assets/mappin.png" mode="aspectFit"></image>
        <text>{{ weather?.city || location }}</text>
        <image src="/static/assets/chevrondown.png" mode="aspectFit"></image>
      </view>

      <!-- 当前天气 -->
      <view class="current-weather">
        <view class="temp-display">
          <view>
            <text class="temp-value">{{ now ? now.temp + '°C' : '--°C' }}</text>
            <text class="temp-desc">{{ now?.text || '加载中' }}</text>
          </view>
          <image :src="now?.text ? getIcon(now.text) : '/static/assets/sun.png'" mode="aspectFit" style="width:64px;height:64px"></image>
        </view>
        <view class="weather-details">
          <view class="wd-item">
            <image src="/static/assets/wind.png" mode="aspectFit"></image>
            <text>{{ now ? now.windSpeed + 'km/h' : '--' }}</text>
          </view>
          <view class="wd-item">
            <image src="/static/assets/droplets.png" mode="aspectFit"></image>
            <text>{{ now ? now.humidity + '%' : '--%' }}</text>
          </view>
        </view>
        <view class="farm-status">
          <image src="/static/assets/checkcircle.png" mode="aspectFit" style="width:18px;height:18px"></image>
          <text>{{ now ? '体感 ' + (now.feelsLike || now.temp) + '°C · ' + (weather?.update_time || '') : '查询中...' }}</text>
        </view>
      </view>

      <!-- 预警 -->
      <view v-if="warning" class="section-card" :style="'border-left:4px solid ' + warning.color + ';margin-bottom:12px'">
        <view class="section-title-row">
          <image src="/static/assets/trianglealert.png" mode="aspectFit" style="width:18px;height:18px"></image>
          <text class="section-title">{{ warning.title }}</text>
        </view>
        <text style="font-size:12px;color:#666;margin-top:4px">{{ warning.text.slice(0, 100) }}...</text>
      </view>

      <!-- 预报 -->
      <view class="section-card">
        <text class="section-title">未来7天预报</text>
        <view class="forecast-grid">
          <view v-for="(d, i) in dailyList" :key="i" class="forecast-day">
            <text class="fd-label">{{ dayLabels[i] || (i + 1 + '') }}</text>
            <image :src="getIcon(d?.textDay)" mode="aspectFit" style="width:24px;height:24px"></image>
            <text class="fd-temp">{{ d ? d.tempMax + '°' : '--°' }}</text>
            <text v-if="d" style="font-size:10px;color:#999;margin-top:2px">{{ getDayDesc(d.textDay) }}</text>
          </view>
        </view>
      </view>

      <!-- 农事建议 -->
      <view v-if="loading" style="text-align:center;padding:24px">
        <text style="color:#999">正在获取农事建议...</text>
      </view>
      <view v-if="advice" class="section-card">
        <view class="advice-header">
          <image src="/static/assets/leaf0.png" mode="aspectFit"></image>
          <text>农事操作建议</text>
        </view>
        <view>
          <view v-for="(point, i) in advicePoints" :key="i" class="advice-item">
            <view class="advice-bullet"></view>
            <text>{{ point }}</text>
          </view>
        </view>
      </view>
    </view>
  </view>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue';
import { agentChat } from '../../utils/api';
import { API } from '../../utils/api';

const loading = ref(false);
const advice = ref('');
const weather = ref(null);
const location = ref('湖南省长沙市');
const showInput = ref(false);
const locInput = ref(location.value);
const dayLabels = ['今', '明', '三', '四', '五', '六', '日'];

const now = computed(() => weather.value?.now || null);
const dailyList = computed(() => {
  const d = weather.value?.daily || [];
  return d.length > 0 ? d : Array(7).fill(null);
});
const advicePoints = computed(() => {
  if (!advice.value) return [];
  return advice.value.split(/\d\./).filter(Boolean);
});

function getIcon(text) {
  if (!text) return '/static/assets/sun.png';
  if (text.includes('晴')) return '/static/assets/sun.png';
  if (text.includes('多云') || text.includes('阴')) return '/static/assets/cloudsun.png';
  if (text.includes('雨') || text.includes('雷') || text.includes('阵')) return '/static/assets/cloudrain.png';
  return '/static/assets/sun.png';
}
function getDayDesc(text) {
  const m = { '晴': '晴', '多云': '多云', '阴': '阴', '小雨': '小雨', '中雨': '中雨', '大雨': '大雨', '暴雨': '暴雨', '雷阵雨': '雷雨', '阵雨': '阵雨' };
  for (const [k, v] of Object.entries(m)) { if (text.includes(k)) return v; }
  return text.slice(0, 2);
}

const warning = computed(() => {
  if (!weather.value?.warning?.length) return null;
  const w = weather.value.warning[0];
  const isRed = w.level === '红色' || w.severity === 'Extreme';
  const isOrange = w.level === '橙色' || w.severity === 'Severe';
  const isYellow = w.level === '黄色' || w.severity === 'Moderate';
  return {
    title: w.title || '',
    text: w.text || '',
    color: isRed ? '#e74c3c' : isOrange ? '#f39c12' : isYellow ? '#f1c40f' : '#3498db',
  };
});

async function fetchWeatherData(loc) {
  try {
    const res = await uni.request({ url: `${API.weather}?region=${encodeURIComponent(loc)}`, method: 'GET', timeout: 60000 });
    if (res.data?.success) weather.value = res.data.data;
  } catch (e) { console.warn('[天气] 请求异常:', e); }
}

async function fetchAdvice(loc) {
  loading.value = true;
  advice.value = '';
  try {
    const reply = await agentChat({ message: `${loc}今天天气怎么样，适合打药吗`, session_id: `weather_${Date.now()}` });
    advice.value = reply;
  } catch { uni.showToast({ title: '获取农事建议失败', icon: 'none' }); }
  finally { loading.value = false; }
}

async function fetchAll(loc) {
  await Promise.all([fetchWeatherData(loc), fetchAdvice(loc)]);
}

function handleLocChange() {
  const loc = locInput.value.trim() || '湖南省长沙市';
  location.value = loc;
  showInput.value = false;
  fetchAll(loc);
}

onMounted(() => { fetchAll(location.value); });
</script>
